$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Assign metastore to workspace
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Basic metastore assignment
      type: DatabricksDsc/DatabricksAccountMetastoreAssignment
      properties:
        AccountId: '12345678-1234-1234-1234-123456789012'
        WorkspaceId: '1234567890123456'
        MetastoreId: '87654321-4321-4321-4321-210987654321'
        AccessToken: '<YourAccountAccessTokenHere>'
