$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create workspace service principal with minimal configuration
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Basic workspace service principal
      type: DatabricksDsc/DatabricksServicePrincipal
      properties:
        WorkspaceUrl: '<workspaceUrl>'
        AccessToken: '<YourAccessTokenHere>'
        ApplicationId: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
        DisplayName: 'My Service Principal'
