$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create cluster policy with minimal configuration
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Basic cluster policy
      type: DatabricksDsc/DatabricksClusterPolicy
      properties:
        WorkspaceUrl: 'https://adb-953475542402434.14.azuredatabricks.net'
        AccessToken: '<YourAccessTokenHere>'
        Name: 'Basic Cluster Policy'
        Definition: '{"spark_version":{"type":"fixed","value":"13.3.x-scala2.12"}}'
