$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create workspace user with minimal configuration
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Basic workspace user
      type: DatabricksDsc/DatabricksUser
      properties:
        WorkspaceUrl: '<workspaceUrl>'
        AccessToken: '<YourAccessTokenHere>'
        UserName: 'user@example.com'
        DisplayName: 'Example User'
