$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create inactive workspace user
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Inactive workspace user
      type: DatabricksDsc/DatabricksUser
      properties:
        WorkspaceUrl: '<workspaceUrl>'
        AccessToken: '<YourAccessTokenHere>'
        UserName: 'inactive.user@example.com'
        DisplayName: 'Inactive User'
        Active: false
