$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create workspace group with members
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Group with user members
      type: DatabricksDsc/DatabricksGroup
      properties:
        WorkspaceUrl: 'https://adb-953475542402434.14.azuredatabricks.net'
        AccessToken: '<YourAccessTokenHere>'
        DisplayName: 'data-engineers'
        Members:
        - Value: '1234567890123456'  # User or group ID
          Display: 'user@example.com'
        - Value: '6543210987654321'
          Display: 'another.user@example.com'
