$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create workspace group with entitlements
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Group with entitlements
      type: DatabricksDsc/DatabricksGroup
      properties:
        WorkspaceUrl: 'https://adb-953475542402434.14.azuredatabricks.net'
        AccessToken: '<YourAccessTokenHere>'
        DisplayName: 'data-engineers'
        Entitlements:
        - Value: 'allow-cluster-create'
        - Value: 'databricks-sql-access'
