$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Create workspace group with all configurable properties
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Complete workspace group configuration
      type: DatabricksDsc/DatabricksGroup
      properties:
        WorkspaceUrl: 'https://adb-953475542402434.14.azuredatabricks.net'
        AccessToken: '<YourAccessTokenHere>'
        DisplayName: 'data-engineers'
        ExternalId: 'external-group-123'
        Entitlements:
        - Value: 'allow-cluster-create'
        - Value: 'allow-instance-pool-create'
        - Value: 'databricks-sql-access'
        Roles:
        - Value: 'arn:aws:iam::123456789012:instance-profile/data-engineer-role'
