$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Remove workspace group
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Ensure group does not exist
      type: DatabricksDsc/DatabricksGroup
      properties:
        WorkspaceUrl: 'https://adb-953475542402434.14.azuredatabricks.net'
        AccessToken: '<YourAccessTokenHere>'
        DisplayName: 'deprecated-group'
        _exist: false
