$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
- name: Remove workspace group
  type: Microsoft.DSC/PowerShell
  properties:
    resources:
    - name: Ensure group does not exist
      type: DatabricksDsc/DatabricksGroup
      properties:
        WorkspaceUrl: '<workspaceUrl>'
        AccessToken: '<YourAccessTokenHere>'
        DisplayName: 'deprecated-group'
        _exist: false
